-- Use the correct database
USE antipromovie;

-- Add seats to ALL screens in the database
-- This script will add 150 seats (10 rows x 15 seats) to each screen
-- Rows A-C: PREMIUM (45 seats)
-- Rows D-G: REGULAR (60 seats)
-- Rows H-J: ECONOMY (45 seats)

-- First, let's clear any existing seats to avoid duplicates
DELETE FROM seats;

-- Insert seats for all screens
INSERT INTO seats (screen_id, `row_number`, seat_number, seat_type)
SELECT 
    s.id as screen_id,
    seat_data.row_number,
    seat_data.seat_number,
    seat_data.seat_type
FROM screens s
CROSS JOIN (
    -- Premium Row A
    SELECT 'A' as row_number, 1 as seat_number, 'PREMIUM' as seat_type UNION ALL
    SELECT 'A', 2, 'PREMIUM' UNION ALL SELECT 'A', 3, 'PREMIUM' UNION ALL SELECT 'A', 4, 'PREMIUM' UNION ALL SELECT 'A', 5, 'PREMIUM' UNION ALL
    SELECT 'A', 6, 'PREMIUM' UNION ALL SELECT 'A', 7, 'PREMIUM' UNION ALL SELECT 'A', 8, 'PREMIUM' UNION ALL SELECT 'A', 9, 'PREMIUM' UNION ALL SELECT 'A', 10, 'PREMIUM' UNION ALL
    SELECT 'A', 11, 'PREMIUM' UNION ALL SELECT 'A', 12, 'PREMIUM' UNION ALL SELECT 'A', 13, 'PREMIUM' UNION ALL SELECT 'A', 14, 'PREMIUM' UNION ALL SELECT 'A', 15, 'PREMIUM' UNION ALL
    -- Premium Row B
    SELECT 'B', 1, 'PREMIUM' UNION ALL SELECT 'B', 2, 'PREMIUM' UNION ALL SELECT 'B', 3, 'PREMIUM' UNION ALL SELECT 'B', 4, 'PREMIUM' UNION ALL SELECT 'B', 5, 'PREMIUM' UNION ALL
    SELECT 'B', 6, 'PREMIUM' UNION ALL SELECT 'B', 7, 'PREMIUM' UNION ALL SELECT 'B', 8, 'PREMIUM' UNION ALL SELECT 'B', 9, 'PREMIUM' UNION ALL SELECT 'B', 10, 'PREMIUM' UNION ALL
    SELECT 'B', 11, 'PREMIUM' UNION ALL SELECT 'B', 12, 'PREMIUM' UNION ALL SELECT 'B', 13, 'PREMIUM' UNION ALL SELECT 'B', 14, 'PREMIUM' UNION ALL SELECT 'B', 15, 'PREMIUM' UNION ALL
    -- Premium Row C
    SELECT 'C', 1, 'PREMIUM' UNION ALL SELECT 'C', 2, 'PREMIUM' UNION ALL SELECT 'C', 3, 'PREMIUM' UNION ALL SELECT 'C', 4, 'PREMIUM' UNION ALL SELECT 'C', 5, 'PREMIUM' UNION ALL
    SELECT 'C', 6, 'PREMIUM' UNION ALL SELECT 'C', 7, 'PREMIUM' UNION ALL SELECT 'C', 8, 'PREMIUM' UNION ALL SELECT 'C', 9, 'PREMIUM' UNION ALL SELECT 'C', 10, 'PREMIUM' UNION ALL
    SELECT 'C', 11, 'PREMIUM' UNION ALL SELECT 'C', 12, 'PREMIUM' UNION ALL SELECT 'C', 13, 'PREMIUM' UNION ALL SELECT 'C', 14, 'PREMIUM' UNION ALL SELECT 'C', 15, 'PREMIUM' UNION ALL
    -- Regular Row D
    SELECT 'D', 1, 'REGULAR' UNION ALL SELECT 'D', 2, 'REGULAR' UNION ALL SELECT 'D', 3, 'REGULAR' UNION ALL SELECT 'D', 4, 'REGULAR' UNION ALL SELECT 'D', 5, 'REGULAR' UNION ALL
    SELECT 'D', 6, 'REGULAR' UNION ALL SELECT 'D', 7, 'REGULAR' UNION ALL SELECT 'D', 8, 'REGULAR' UNION ALL SELECT 'D', 9, 'REGULAR' UNION ALL SELECT 'D', 10, 'REGULAR' UNION ALL
    SELECT 'D', 11, 'REGULAR' UNION ALL SELECT 'D', 12, 'REGULAR' UNION ALL SELECT 'D', 13, 'REGULAR' UNION ALL SELECT 'D', 14, 'REGULAR' UNION ALL SELECT 'D', 15, 'REGULAR' UNION ALL
    -- Regular Row E
    SELECT 'E', 1, 'REGULAR' UNION ALL SELECT 'E', 2, 'REGULAR' UNION ALL SELECT 'E', 3, 'REGULAR' UNION ALL SELECT 'E', 4, 'REGULAR' UNION ALL SELECT 'E', 5, 'REGULAR' UNION ALL
    SELECT 'E', 6, 'REGULAR' UNION ALL SELECT 'E', 7, 'REGULAR' UNION ALL SELECT 'E', 8, 'REGULAR' UNION ALL SELECT 'E', 9, 'REGULAR' UNION ALL SELECT 'E', 10, 'REGULAR' UNION ALL
    SELECT 'E', 11, 'REGULAR' UNION ALL SELECT 'E', 12, 'REGULAR' UNION ALL SELECT 'E', 13, 'REGULAR' UNION ALL SELECT 'E', 14, 'REGULAR' UNION ALL SELECT 'E', 15, 'REGULAR' UNION ALL
    -- Regular Row F
    SELECT 'F', 1, 'REGULAR' UNION ALL SELECT 'F', 2, 'REGULAR' UNION ALL SELECT 'F', 3, 'REGULAR' UNION ALL SELECT 'F', 4, 'REGULAR' UNION ALL SELECT 'F', 5, 'REGULAR' UNION ALL
    SELECT 'F', 6, 'REGULAR' UNION ALL SELECT 'F', 7, 'REGULAR' UNION ALL SELECT 'F', 8, 'REGULAR' UNION ALL SELECT 'F', 9, 'REGULAR' UNION ALL SELECT 'F', 10, 'REGULAR' UNION ALL
    SELECT 'F', 11, 'REGULAR' UNION ALL SELECT 'F', 12, 'REGULAR' UNION ALL SELECT 'F', 13, 'REGULAR' UNION ALL SELECT 'F', 14, 'REGULAR' UNION ALL SELECT 'F', 15, 'REGULAR' UNION ALL
    -- Regular Row G
    SELECT 'G', 1, 'REGULAR' UNION ALL SELECT 'G', 2, 'REGULAR' UNION ALL SELECT 'G', 3, 'REGULAR' UNION ALL SELECT 'G', 4, 'REGULAR' UNION ALL SELECT 'G', 5, 'REGULAR' UNION ALL
    SELECT 'G', 6, 'REGULAR' UNION ALL SELECT 'G', 7, 'REGULAR' UNION ALL SELECT 'G', 8, 'REGULAR' UNION ALL SELECT 'G', 9, 'REGULAR' UNION ALL SELECT 'G', 10, 'REGULAR' UNION ALL
    SELECT 'G', 11, 'REGULAR' UNION ALL SELECT 'G', 12, 'REGULAR' UNION ALL SELECT 'G', 13, 'REGULAR' UNION ALL SELECT 'G', 14, 'REGULAR' UNION ALL SELECT 'G', 15, 'REGULAR' UNION ALL
    -- Economy Row H
    SELECT 'H', 1, 'ECONOMY' UNION ALL SELECT 'H', 2, 'ECONOMY' UNION ALL SELECT 'H', 3, 'ECONOMY' UNION ALL SELECT 'H', 4, 'ECONOMY' UNION ALL SELECT 'H', 5, 'ECONOMY' UNION ALL
    SELECT 'H', 6, 'ECONOMY' UNION ALL SELECT 'H', 7, 'ECONOMY' UNION ALL SELECT 'H', 8, 'ECONOMY' UNION ALL SELECT 'H', 9, 'ECONOMY' UNION ALL SELECT 'H', 10, 'ECONOMY' UNION ALL
    SELECT 'H', 11, 'ECONOMY' UNION ALL SELECT 'H', 12, 'ECONOMY' UNION ALL SELECT 'H', 13, 'ECONOMY' UNION ALL SELECT 'H', 14, 'ECONOMY' UNION ALL SELECT 'H', 15, 'ECONOMY' UNION ALL
    -- Economy Row I
    SELECT 'I', 1, 'ECONOMY' UNION ALL SELECT 'I', 2, 'ECONOMY' UNION ALL SELECT 'I', 3, 'ECONOMY' UNION ALL SELECT 'I', 4, 'ECONOMY' UNION ALL SELECT 'I', 5, 'ECONOMY' UNION ALL
    SELECT 'I', 6, 'ECONOMY' UNION ALL SELECT 'I', 7, 'ECONOMY' UNION ALL SELECT 'I', 8, 'ECONOMY' UNION ALL SELECT 'I', 9, 'ECONOMY' UNION ALL SELECT 'I', 10, 'ECONOMY' UNION ALL
    SELECT 'I', 11, 'ECONOMY' UNION ALL SELECT 'I', 12, 'ECONOMY' UNION ALL SELECT 'I', 13, 'ECONOMY' UNION ALL SELECT 'I', 14, 'ECONOMY' UNION ALL SELECT 'I', 15, 'ECONOMY' UNION ALL
    -- Economy Row J
    SELECT 'J', 1, 'ECONOMY' UNION ALL SELECT 'J', 2, 'ECONOMY' UNION ALL SELECT 'J', 3, 'ECONOMY' UNION ALL SELECT 'J', 4, 'ECONOMY' UNION ALL SELECT 'J', 5, 'ECONOMY' UNION ALL
    SELECT 'J', 6, 'ECONOMY' UNION ALL SELECT 'J', 7, 'ECONOMY' UNION ALL SELECT 'J', 8, 'ECONOMY' UNION ALL SELECT 'J', 9, 'ECONOMY' UNION ALL SELECT 'J', 10, 'ECONOMY' UNION ALL
    SELECT 'J', 11, 'ECONOMY' UNION ALL SELECT 'J', 12, 'ECONOMY' UNION ALL SELECT 'J', 13, 'ECONOMY' UNION ALL SELECT 'J', 14, 'ECONOMY' UNION ALL SELECT 'J', 15, 'ECONOMY'
) AS seat_data;

-- Verify the results
SELECT 
    sc.id as screen_id,
    t.name as theatre_name,
    sc.screen_number,
    COUNT(st.id) as total_seats,
    SUM(CASE WHEN st.seat_type = 'PREMIUM' THEN 1 ELSE 0 END) as premium_seats,
    SUM(CASE WHEN st.seat_type = 'REGULAR' THEN 1 ELSE 0 END) as regular_seats,
    SUM(CASE WHEN st.seat_type = 'ECONOMY' THEN 1 ELSE 0 END) as economy_seats
FROM screens sc
LEFT JOIN theatres t ON sc.theatre_id = t.id
LEFT JOIN seats st ON sc.id = st.screen_id
GROUP BY sc.id, t.name, sc.screen_number
ORDER BY sc.id;

-- Show total seats added
SELECT COUNT(*) as total_seats_in_database FROM seats;
